spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform:  org.hibernate.dialect.PostgreSQL95Dialect
  datasource:
    url:  jdbc:postgresql://localhost:5432/sap
    username: sap
    password: sap


  security:
    oauth2:
      client:
        registration:
          google:
            client-id:  1087253594794-sbtlrc4nka9nnntsbphnein9lqe0f8tu.apps.googleusercontent.com
            client-secret: 6oWPZ9alQNGJOKVmphftXIwR